---
- name: create a demo server
  hosts: localhost
  gather_facts: False
  vars:
    cpu_size: 1
    memory_size: 1 
    system_name: asrvr
    default_password: 'efgH345#$%'
  tasks:
    - name: Build my server
      clc_server:
        name: "{{ system_name }}" 
        template: UBUNTU-14-64-TEMPLATE
        cpu: "{{ cpu_size }}" 
        memory: "{{ memory_size }}" 
        location: 'CA2'
        group: 'Default Group'
        count: 1
        password: "{{ default_password }}"
      register: my_srvr
    - debug: var=my_srvr
