---
- name: Create a demo server playbook
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a demo server play
      clc_server:
        name: msrvr
        template: UBUNTU-14-64-TEMPLATE
        cpu: 1
        memory: 1
        location: 'CA2'
        group: 'Default Group'
        count: 1
        password: fgh567%^&
      register: my_server
    - debug: var=my_server
