---
- name: Create a demo server playbook
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a demo server play
      clc_server:
        name: msrvr
        template: UBUNTU-14-64-TEMPLATE
        cpu: 1
        memory: 1
        group: 'Default Group'
        location: 'CA2'
        count: 1
        password: 'Fgh456!@#'
      register: my_srvr
    - debug: var=my_srvr
